branch-defaults:
  main:
    environment: laravel-environment

deploy:
  artifact: Dockerrun.aws.json

environment-defaults:
  laravel-environment:
    branch: null
    repository: null

global:
  application_name: laravel-realworld-example-app
  default_ec2_keyname: laravel-readlworld-example-app
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application

option_settings:
  - namespace: aws:elasticbeanstalk:environment:process:default
    option_name: HealthCheckPath
    value: "/"
  - namespace: aws:elasticbeanstalk:environment:process:default
    option_name: Port
    value: "80"
  - namespace: aws:elasticbeanstalk:environment:process:default
    option_name: LogFile
    value: /var/log/apache2/access.log
