name: Deploy to Dev

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy-to-staging-env:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-west-2'         
      - name: setup aws-eb-cli
        uses: tristanbarlow/setup-elasticbeanstalk-cli@v1.0.0
      - run: |
          eb init -p docker "${{ secrets.APPLICATION_NAME }}"
          eb create ${{ secrets.ENVIRONMENT_NAME_STAGING }} || eb deploy ${{ secrets.ENVIRONMENT_NAME_STAGING }}
